services:
  m169_container:
    image: pablo06/m169-container-webserver
    container_name: pablos-container
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data:/usr/share/nginx/html
